### ISSUE TITLE
T-radio-group notreactive to v-model (or input event)

### ISSUE THREAD

**Issue by Lacroute** [alfonsobries/vue-tailwind#100]
Hi,

Seems like `localValue` is not correctly binded to `t-radio`
link: [https://codesandbox.io/s/vibrant-cartwright-hcjxc?file=/src/App.vue](https://codesandbox.io/s/vibrant-cartwright-hcjxc?file=/src/App.vue)

**Comment by alfonsobries** [comment]
@Lacroute you need to use `v-model` to make it reactive

**Comment by alfonsobries** [comment]
@Lacroute fixed @ 1.3.2
