### ISSUE TITLE
Disable options in TSelect

### ISSUE THREAD

**Issue by NikODipS** [alfonsobries/vue-tailwind#103]
Hey buddy, 
I'm using your amazing creation and, let me tell you, You did some really cool stuff.

Anyway, I bumped into some issue, I'm using the TSelect component (actually the the TRich one but with no axios) and there is no way I can disable some option. 

There's no way to do it, or I'm just too blind too see it?

That'll be really nice to have, cause sometime you wanna show options that user can't select for he has no permission to, but you wanna show 'em anyway.

Thanks.

**Comment by alfonsobries** [comment]
@NikODipS That was an important feature and was added in `v1.3.3`, you just to add a `disabled: true` attribute to your list of options (only works for array format https://www.vue-tailwind.com/docs/select#array-of-objects).

Also, this version adds a new `disabledOption` class for the rich select component that now also accepts disabled options,

The docs should be updated at any moment mentioning that

**Comment by NikODipS** [comment]
Oh thank you so much,

I just realized I'm using the 1.3.0.

Thanks
