### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by rashidpathiyil** [alfonsobries/vue-tailwind#106]
### 1. Navigation Drawer
It's really essential to have a navigation drawer which supports swipe left or right on the window of mobile devices to toggle it.

### 2. App-bar
It's also really helpful if we have an app bar with different behavior on scrolling like fixed, a shadow on a scroll, and hide on the scroll. add a prop to inject classes(shadow, border) that should add when scrolling happens.

Regards
Rashid Pathiyil

**Comment by alfonsobries** [comment]
Hi, @rashidpathiyil thanks for your proposal, ill keep it in mind but for now I don't think ill create those components, at least not for now because of other priorities.
