### ISSUE TITLE
enableBodyScroll unsuccessful on v2

### ISSUE THREAD

**Issue by igerslike** [alfonsobries/vue-tailwind#107]
Hey, thanks a lot for the amazing plugin, iv been using since v1 and today i have attempted to updated to v2 beta, and it was a breeze. 

Just noticed a little error on the console that seems to root on TModal Component, and wanted to report, not sure if you have noticed: 

`enableBodyScroll unsuccessful - targetElement must be provided when calling enableBodyScroll on IOS devices`

Node 12
VueTailwind 2.0.01
Vue 2

Not sure if this is already fixed on the current pull request but let me know if something needs to be done or set any option.

Once again thanks for the amazing work! :) Keep it up.

**Comment by D-Marc1** [comment]
I did `:disable-body-scroll="false"`, but it didn't change anything for me.

**Comment by igerslike** [comment]
@D-Marc1  on the modal component?

**Comment by D-Marc1** [comment]
Yes, I'm using the modal component. I now see I misread your post actually, as I'm using v1.3, and your question is about v2.

**Comment by igerslike** [comment]
Yeah, but thanks for pointing this out, ill check if that works for me as temporary fix, otherwise will rollback back to 1.x until stable 👍

**Comment by ElPapi42** [comment]
Same problem here

**Comment by alfonsobries** [comment]
@igerslike _maybe_ was fixed on`2.0.0-2` didn't make a comprehensive test,

**Comment by alfonsobries** [comment]
Btw 2.0 will include a default theme that still is a WIP so some components may look different if you didn't override the theme

**Comment by ElPapi42** [comment]
that default theme will be awesome

**Comment by igerslike** [comment]
A quick update here. Adding `:disableBodyScroll="false"` supresses the error, because it seems like it ignored the IF condition here :

https://github.com/alfonsobries/vue-tailwind/blob/ff241564694f868ef23a5a9665673da98f84ed20/src/components/TDialog.ts#L268

Also not sure if that matters but im using Vue-Portal to delivery the modals.

**Comment by alfonsobries** [comment]
Just released v2 that should fix that problem, let me know @igerslike

**Comment by alfonsobries** [comment]
@igerslike I'm gonna close this ticket for now but feel free to open it again if you still see the issue
