### ISSUE TITLE
Is it possible to add an icon to a button?

### ISSUE THREAD

**Issue by robertfausk** [alfonsobries/vue-tailwind#111]
...via using a slot or something else?

E.g. like in bootstrap-vue:
https://bootstrap-vue.org/docs/icons#buttons

**Comment by alfonsobries** [comment]
not sure If I get your question @robertfausk the button component renders a simple <button> you can add your icon inside:

```
<t-button>[the text] [the icon]</t-button>
```

**Comment by robertfausk** [comment]
@alfonsobries Yep. You are right. It's working like a charm!

```VUE
<t-button
  class="w-full flex items-center justify-center group"
  variant="primary"
>
  <printer-icon
    class="mr-2 group-hover:animate-bounce"
    size="26"
  />
  Poster drucken
</t-button>
```

WDYT about adding this use case to the docs?
