### ISSUE TITLE
Tailwind v2 Support?

### ISSUE THREAD

**Issue by A-Lawrence** [alfonsobries/vue-tailwind#112]
Howdy!

Just enquiring as to whether you'll be releasing a version that uses Tailwind v2?

**Comment by alfonsobries** [comment]
> Howdy!
> 
> 
> 
> Just enquiring as to whether you'll be releasing a version that uses Tailwind v2?

Yes, I am about to release v2 that uses tailwind 2 classes by default, however in theory the current version should also work with tailwind 1.0 (or any css framework) since you can define the css classes

**Comment by mous2890** [comment]
Will the new version contain datatables features?

**Comment by alfonsobries** [comment]
@mous2890 no only the features the current table component has

**Comment by alfonsobries** [comment]
@A-Lawrence just released v2.0 that with a tailwind 2.0 theme https://www.vue-tailwind.com/
