### ISSUE TITLE
[Feature request] Loading component

### ISSUE THREAD

**Issue by harrytran998** [alfonsobries/vue-tailwind#115]
I think loading it's the popular stuff in a product. So hope you can implement this in the feature bro!

**Comment by alfonsobries** [comment]
@harrytran998 the thing with the loading component is that are hundreds of ways to do it, like using an animated icon or SVG or even a gif, in other cases is a progress bar or a progress circle.

Most of them are not directly related to CSS, for example, my favorite kind of loaders are SVGs, those are not related to CSS  classes so doesn't make sense as part of this library.

mm, maybe a progress bar will work here, need to think about it🤔
