### ISSUE TITLE
Label attribute "for".

### ISSUE THREAD

**Issue by vasia123** [alfonsobries/vue-tailwind#116]
I found mention to this parameter in code 

https://github.com/alfonsobries/vue-tailwind/blob/2d67b982595fcda5b70d5f30314fca6bc2333586/src/components/TInputGroup.ts#L9

which refers to setup "for" attribute

https://github.com/alfonsobries/vue-tailwind/blob/2d67b982595fcda5b70d5f30314fca6bc2333586/src/components/TInputGroup.ts#L72

 but my code not working:
```html
<t-input-group label="Title" input-name="title">
    <t-input type="text" name="title"  />
</t-input-group>
``` 
how can i set "for" attribute of label?

**Comment by alfonsobries** [comment]
@vasia123 weird it should be working, ill take a look later today thanks for the report

**Comment by alfonsobries** [comment]
@vasia123 just tested your exact example and it's working fine for me, is there any way that I can replicate the issue?

**Comment by alfonsobries** [comment]
@vasia123 I am gonna close this ticket for now since I cannot replicate the issue, feel 100% free to open it again if the problem persists.
