### ISSUE TITLE
Is there a simple way to deactivate all past days in the datepicker?

### ISSUE THREAD

**Issue by handplant** [alfonsobries/vue-tailwind#117]
As it is possible in this component [https://github.com/charliekassel/vuejs-datepicker#disabled-dates](https://github.com/charliekassel/vuejs-datepicker#disabled-dates)

Thx

**Comment by alfonsobries** [comment]
@handplant yes, the `disableDates` prop accepts a function https://www.vue-tailwind.com/docs/datepicker#disable-dates

So you can do something like this

```
<t-datepicker
            placeholder="Pick a date"
            :disabled-dates="(date) => {
              return date <= new Date()
            }"
          />
```

**Comment by alfonsobries** [comment]
@handplant just remember that you can also use the `minDate` prop that even easier

```
<t-datepicker :min-date="new Date()" />
```

**Comment by alfonsobries** [comment]
@handplant I am goona close the ticket, for now, feel free to open it again if you have more issues
