### ISSUE TITLE
Rich Select with multi-select

### ISSUE THREAD

**Issue by gebrits** [alfonsobries/vue-tailwind#121]
Is it possible to have a Rich Selector with multi-select enabled? 

It's available in the docs for a [normal select](https://www.vue-tailwind.com/docs/select) but not for [Rich Select](https://www.vue-tailwind.com/docs/rich-select)

**Comment by alfonsobries** [comment]
@gebrits this will be my next priority, I'll take a couple of days off the next week and this is a tricky task so probably will not ready on the next week though but I'll do my best

**Comment by restyler** [comment]
Can anyone share any lightweight alternatives to rich select which support multiple and play good with Vue Tailwind? I need it, too.

**Comment by alfonsobries** [comment]
@gebrits @restyler good news I just published v 2.1.0 with the new `multiple` prop 

https://www.vue-tailwind.com/docs/rich-select/#multi-select
