### ISSUE TITLE
Inputs don't allow event propagation

### ISSUE THREAD

**Issue by Lacroute** [alfonsobries/vue-tailwind#123]
Hi,

I discovered that I can't listen to custom events on t-input.

[Reproduction link](https://codesandbox.io/s/beautiful-khorana-nbhuw?file=/src/App.vue)

**Why do I want to do this?**
I'm using the google autocomplete place API. Because I need abstraction, I created my own event to listen to when google answers me. I can use a [EventTarget](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/EventTarget) object to dialog with or simply use the inputs and trigger some custom events.

According to the [doc](https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components) there is a way to do it.

**Comment by alfonsobries** [comment]
@Lacroute sorry for the delay and thanks for the report, this issue should be fixed on v2.0.1
