### ISSUE TITLE
TCheckbox infinite loop

### ISSUE THREAD

**Issue by NikODipS** [alfonsobries/vue-tailwind#124]
<pre>&lt;template&gt;
    &lt;div @click="toggle"&gt;
        &lt;t-checkbox :checked="checked"&gt;&lt;/t-checkbox&gt;
    &lt;/div&gt;
&lt;/template&gt;

&lt;script&gt;
    export default {
        data(){
            return {
                checked: false
            }
        },
        methods: {
            toggle(){
                this.checked = !this.checked;
                console.log("LOOP");
            }
        }
    }
&lt;/script&gt;</pre>

If I click on the checkbox, it goes in an infinite loop. probably the click propagation event  should be stopped

**Comment by alfonsobries** [comment]
@NikODipS you can stop the event propagation on the wrapper

```
<div @click.stop="toggle">
        <t-checkbox :checked="checked"></t-checkbox>
    </div>
```

**Comment by alfonsobries** [comment]
Closing this since I didn't receive more feedback
