### ISSUE TITLE
`t-button` doesn't convert to `inertia-link`?

### ISSUE THREAD

**Issue by sbrow** [alfonsobries/vue-tailwind#126]
In the docs it says `t-button` should convert to an `inertia-link` when inertia is present and href is set. This isn't working for me.

```vue
<template>
  <t-button href="/test">Reset(?)</t-button>
  <inertia-link href="/test">Reset</inertia-link>
</template>
```

When I use the dev tools, nothing appears under the t-button, and the link does not work as expected.

# Version info
- **vue:** 2.6.12
- **vue-tailwind:** 2.0.0
- **InertiaJs:** 0.5.4

**Comment by alfonsobries** [comment]
@sbrow the docs had a mistake, you also need to change the `tagName` to `'a'`.

I just update the docs and added a tip to make that easy. https://www.vue-tailwind.com/docs/button#inertiajs-compatibility

```html
<t-button tag-name="a" href="/something">Button</t-button>`

**Comment by zorca** [comment]
> 
> 
> @sbrow the docs had a mistake, you also need to change the `tagName` to `'a'`.
> 
> I just updated the docs and added a tip to make that easy. https://www.vue-tailwind.com/docs/button#inertiajs-compatibility
> 
> ```
> <t-button tag-name="a" href="/something">Button</t-button>`
> ```

Thank you!
