### ISSUE TITLE
Unable to use vue-tailwind in nuxt generated app

### ISSUE THREAD

**Issue by fparaggio** [alfonsobries/vue-tailwind#128]
In my nuxt.js project I am using the datepicker. I import the library as a plugin in this way:

/plugins/vue-tailwind.js
```javascript
import Vue from 'vue'
import VueTailwind from 'vue-tailwind'
Vue.use(VueTailwind)
```

/nuxt.config.js
```javascript
plugins: ['~plugins/vue-tailwind']
```

and the component works perfectly in development.

My problem is that the component is not rendered when I serve the app generated with

```
nuxt generate
```

I already tried to load the plugin this way:
```javascript
{ src: '~plugins/vue-tailwind', mode:  'client' }
```

and also tried to put the component between client-only tag
```html
<client-only>
            <t-datepicker
              v-model="date"
              :max-date="today"
              placeholder="Select a date"
              date-format="Y-m-d"
              user-format="d-M-Y"
            />
</client-only>
```

**Comment by fparaggio** [comment]
there is also a stackoverflow here https://stackoverflow.com/questions/65740711/vue-plugin-not-loaded-on-static-site-generated-by-nuxt if somebody solves this issue

**Comment by alfonsobries** [comment]
Are you only using the date picker? @fparaggio

**Comment by karanjamutahi** [comment]
+1

I am using the [tables](https://www.vue-tailwind.com/docs/table/) in my app but it's not getting built on nuxt generate. The build step succeeds but the table is not being rendered.

**Comment by zorca** [comment]
> 
> 
> +1
> 
> I am using the [tables](https://www.vue-tailwind.com/docs/table/) in my app but it's not getting built on nuxt generate. The build step succeeds but the table is not being rendered.

Are you using Next in ssr or spa mode?

**Comment by alfonsobries** [comment]
ok think that maybe the documentation is not clear think I'm gonna revisit it, meanwhile since version 2 of this library you need to manually import the components since any of them are added by default, if you are only using one component the best way to do it is like its explained here https://www.vue-tailwind.com/docs/installation#33-or-you-can-install-only-the-components-you-need, so for the datepicker the configuration in `/plugins/vue-tailwind.js` should look like this:

```
import Vue from 'vue'
import VueTailwind from 'vue-tailwind'

import TDatepicker from 'vue-tailwind/dist/t-datepicker'


const settings = {
  't-datepicker': {
    component: TDatepicker,
   // here you add your classes config, etc
    props: {}
  },
}

Vue.use(VueTailwind, settings)
```

@fparaggio @karanjamutahi let me know if that solves your problem so I can close this issue

**Comment by fparaggio** [comment]
I am not sure it solves the problem. I solved using ```Vue.component```. It
seems that ```Vue.use``` does not properly work in standalone mode

**Comment by alfonsobries** [comment]
@fparaggio what do you mean by you are not sure, did you test it? the problem with vue.use is that it not applies the global configuration

**Comment by alfonsobries** [comment]
Closing this since no more feedback received feel free to open again if still have the issue
