### ISSUE TITLE
Animate Alert component

### ISSUE THREAD

**Issue by jaulz** [alfonsobries/vue-tailwind#129]
First of all, thanks for this great library! 😊  

Though, what I wondered about is whether there is an easy way to animate the opacity of the `Alert` component whenever it appears/disappears. Thanks for any hints!

**Comment by alfonsobries** [comment]
Not directly at the moment with one prop or class (ill add this feature in my to-do list) 

Still, you can achieve an animation by using transition features from vue.
(see https://vuejs.org/v2/guide/transitions.html#Transitioning-Single-Elements-Components)

Example

```js
<template>
  <div>
    <transition name="slide-fade">
      <t-alert :show="show">
        My Alert
      </t-alert>
    </transition>

    <button @click="show = !show">
      Toggle alert
    </button>
  </div>
</template>

<script>
import Vue from 'vue'

export default {
  data () {
    return {
      show: false
    }
  }
}
</script>

<style>
/* based on https://vuejs.org/v2/guide/transitions.html#CSS-Transitions */
/* Enter and leave animations can use different */
/* durations and timing functions.              */
.slide-fade-enter-active {
  transition: all .3s ease;
}
.slide-fade-leave-active {
  transition: all .8s cubic-bezier(1.0, 0.5, 0.8, 1.0);
}
.slide-fade-enter, .slide-fade-leave-to
/* .slide-fade-leave-active below version 2.1.8 */ {
  transform: translateX(10px);
  opacity: 0;
}
</style>

```

**Comment by jaulz** [comment]
Great, thanks! 😊

**Comment by blaadje** [comment]
> ill add this feature in my to-do list

looking for this feature as well
