### ISSUE TITLE
[Feature] Navigation drawer

### ISSUE THREAD

**Issue by natecorkish** [alfonsobries/vue-tailwind#13]
So for the new issue, I'm working on a navigation drawer, is that something you'd be interested in?

Here's some screenshots  of what I have up to now;

**Left:**

<img src="https://i.imgur.com/AMQPXPq.png">

**Right:**

<img src="https://i.imgur.com/xZiHQh6.png">

**Bottom**

<img src="https://i.imgur.com/JZW4JbC.png">

**Top**

<img src="https://i.imgur.com/7V08rvs.png">

**Fullscreen**

<img src="https://i.imgur.com/HSn7hs7.png">

Props:

- ```position``` left/right/bottom/top
- ```fullscreen``` bool
- ```header``` bool (visible header)

Events:

- ```show```
- ```dismissed```

Slots:

- ```header-content```
- ```activator``` (can be anything)

**Example usage**

````
<drawer
	fullscreen
	@dismiss="dismiss"
>
	<t-button slot="activator"
		slot-scope="scope"
		@click="scope.toggle"
		size="sm"
		class="ml-2"
	>
		Show Notifications.
	</t-button>
	<template slot="content">
		<ul class="mt-2 text-sm text-gray-700 h-full">
			<li v-for="alert in alerts"
				class="pl-6 py-2 flex border-b"
				:key="alert.name"
			>
				<span>
					<i class="mdi mr-3 text-lg" :class="alert.icon"></i>
				</span>
				<div class="flex flex-col">
					<span v-text="alert.name"></span>
					<span
						v-text="alert.date"
						class="text-xs text-gray-500"
					></span>
				</div>
			</li>
		</ul>
	</template>
</drawer>
````

**Comment by alfonsobries** [comment]
Yeah like it

**Comment by alfonsobries** [comment]
I will close this since is not an issue, but again I like the idea

**Comment by zefexdeveloper** [comment]
@natecorkish can you share the code? I really want that drawer. Thank you
