### ISSUE TITLE
Rich Select Multiple Select

### ISSUE THREAD

**Issue by edwinencomienda** [alfonsobries/vue-tailwind#130]
If this component supports it this will be awesome and perfect for most of the applications 😎

**Comment by edwinencomienda** [comment]
We are using this package in our app and we are so happy! that’s only thing that we need and this package 📦 will be the best!

**Comment by alfonsobries** [comment]
@edwinencomienda yeah I have that feature in mind and it's my first priority, I being a little busy with my work and  working on the next version of the package but ill will try to release this feature as soon as I can

**Comment by alfonsobries** [comment]
@edwinencomienda good news I added this feature on version `2.1.0` see the docs https://www.vue-tailwind.com/docs/rich-select/#multi-select

**Comment by edwinencomienda** [comment]
wow @alfonsobries you're the man! thanks a lot!!!! thank you for the hardwork!
