### ISSUE TITLE
CheckboxGroup not working after upgrading to 2.0.1

### ISSUE THREAD

**Issue by Blatty** [alfonsobries/vue-tailwind#132]
Hey @alfonsobries,

Thank you so much for this lib!

I just noticed the CheckboxGroup is breaking with the last update, here's the repro: https://codesandbox.io/s/quiet-leaf-fl48q?file=/pages/index.vue

**Comment by alfonsobries** [comment]
Hey thanks for the report ill fix it during the day @Blatty

**Comment by alfonsobries** [comment]
fixed @ 2.0.2
