### ISSUE TITLE
TSelect is working with WARNING when I bind it with `v-model`

### ISSUE THREAD

**Issue by zhang9553** [alfonsobries/vue-tailwind#135]
Hi @alfonsobries,
It was working fine in v2.0.0 but since 2.0.1 t-select does not seem to work properly with `v-model`.
[Vue warn]: Invalid prop: type check failed for prop "value". Expected Array, String, Number, got Event
Thank you!

**Comment by alfonsobries** [comment]
Hey thanks for the report @zhang9553 ill take care tomorrow

**Comment by zhang9553** [comment]
Hi Alfonso Bribiesca,

Thank you for your response.
I appreciated to your great work!
Have a great weekend.

Best Regards,
Zhang He

**Comment by alfonsobries** [comment]
@zhang9553 should be fixed on 2.1.1

**Comment by zhang9553** [comment]
It works great!
Thank you
