### ISSUE TITLE
Modal sizes

### ISSUE THREAD

**Issue by nlv-edwinencomienda** [alfonsobries/vue-tailwind#137]
how would a extend the size of the modal?

**Comment by Jalx** [comment]
You can change the appearance of the modal using the classes props. For example, using the wrapper class:

`<t-modal v-model="showModal"`
    `:fixedClasses="{`
        `close: 'flex items-center justify-center',`
        `modal: 'overflow-visible relative',`
       `overlay: 'overflow-auto scrolling-touch left-0 top-0 bottom-0 right-0 w-full h-full fixed',`
       `wrapper: 'relative mx-auto z-50 max-w-xl px-3 py-12',`
      `}"`
`>`

The default wrapper class for the modal is `wrapper: 'relative mx-auto z-50 max-w-lg px-3 py-12',`, I changed the `max-w-lg` class for `max-w-xl`

Take a look at tailwind docs for more info for the max-width class: https://tailwindcss.com/docs/max-width#class-reference

More theming info: https://www.vue-tailwind.com/docs/theming#format

Hope it helps, cheers!
