### ISSUE TITLE
'query' is defined but never used

### ISSUE THREAD

**Issue by kek7198** [alfonsobries/vue-tailwind#139]
I'm exploring the rich-select example that uses the Github API to search repos. This one specifically, https://github.com/alfonsobries/vue-tailwind-docs/blob/master/components/examples/rich-select/RichSelectOptionSlot.vue.

I gave it a test run in my vue project but on build, I'm getting an error: 'query' is defined but never used.

Now, I remove query but then selection doesn't work properly. If I select one item, all are selected.

Thanks for this awesome library btw!

**Comment by alfonsobries** [comment]
@kek7198 I leave the  `query` as an example so the user know that they can use it, you can just safely remove that variable and your linter will stop yelling
