### ISSUE TITLE
[bug] Custom Modal theme not working with dist files

### ISSUE THREAD

**Issue by natecorkish** [alfonsobries/vue-tailwind#14]
**src/main.js**

```
import Vue from 'vue';
import app from '@core/app';
import router from '@plugins/router/router';
import store from '@plugins/state/';
import './js/registerServiceWorker';
import './assets/sass/tailwind.scss';
import './js/plugins/vuetailwind'
Vue.config.productionTip = true;

new Vue({
	store,
	router,
	render: h => h(app),
}).$mount('#app');
```

**js/plugins/vuetailwind**

```
import Vue from 'vue';
import VueTailwind from 'vue-tailwind';
import TModal from './modal';

Vue.use(VueTailwind, {
	theme: {
		TModal
	}
});

```

**modal.js**

```
const TModal = {
	baseClass: 'z-40 overflow-auto left-0 top-0 bottom-0 right-0 w-full h-full fixed text-primary',
	overlayClass: 'z-40 overflow-auto left-0 top-0 bottom-0 right-0 w-full h-full fixed bg-black opacity-75',
	containerClass: 'z-50 relative p-3 mx-auto my-0 max-w-full',
	closeIconClass: 'fill-current h-6 w-6 absolute right-0 top-0 m-6',
	wrapperClass: 'bg-primary rounded shadow-lg border flex flex-col overflow-hidden',
	headerClass: 'bg-secondary px-6 py-3 text-xl border-b',
	bodyClass: 'text-primary p-6 flex-grow',
	footerClass: 'bg-secondary px-6 py-3 border-t',
};

export default TModal
```

It doesn't work, but when I change it from : 

```
import VueTailwind from 'vue-tailwind'
```

to:

```
import VueTailwind from 'vue-tailwind/src/index'
````

My custom theme works, I'm not sure if this is intentional or not because of the docs doesn't include the /src/index part

<img src="https://i.imgur.com/x3l2fCc.png">

https://vue-tailwind.com/#install-and-use

**Comment by alfonsobries** [comment]
Hi, yeah should be an error, I will try to fix it in later today

**Comment by alfonsobries** [comment]
Cannot replicate the problem even create a fresh application, are you using the latest version of the package (0.1.27)

**Comment by natecorkish** [comment]
> Cannot replicate the problem even create a fresh application, are you using the latest version of the package (0.1.27)

Yep. Using:

```
"vue-tailwind": "^0.1.27",
```

I've just checked, it's not just modals, it seems to be for all custom themes.


`import VueTailwind from 'vue-tailwind'`

<img src="https://i.imgur.com/2Co5qc4.png">

`import VueTailwind from 'vue-tailwind/src/index'`

<img src="https://i.imgur.com/ARWhlJE.png">

**Comment by natecorkish** [comment]
Give this repo a clone, and see: https://github.com/natecorkish/bugreport

You can edit `src/js/plugins/vuetailwind/index.js`

**Comment by alfonsobries** [comment]
cool that will be helpful @natecorkish, again I will try to spend some time later today

**Comment by alfonsobries** [comment]
Should be fixed now, try to download the latest version
