### ISSUE TITLE
Textarea not clearing in combination with vform

### ISSUE THREAD

**Issue by xewl** [alfonsobries/vue-tailwind#140]
While using [vform](https://github.com/cretueusebiu/vform) I've noticed that clearing/resetting the Form does work with `<t-input ...>` etc,

But it doesn't seem to clear the value inside the `<t-textarea ...>` element in that same case.
Fields are linked with `v-model="form.fieldname"`

Even though the form data resets, the `<t-textarea ...>` element seems to keep the current content, until an update/input is triggered.

Peculiar note:
when combining a `t-input` with _the same v-model_, it does the clearing _on both_ components just fine.
This might be an issue with vform itself in that case too. (Not correctly identifying the textarea component on its own.)

Note that this issue probably needs more info, and I'm willing to provide whatever I can.

**Comment by alfonsobries** [comment]
hey @xewl thanks for the report, should be fixed in `2.1.2` feel free to open the issue again if that doesnt work

**Comment by xewl** [comment]
It works, btw, thanks for both updates ;)
