### ISSUE TITLE
Datetimepicker

### ISSUE THREAD

**Issue by Reached** [alfonsobries/vue-tailwind#141]
Awesome library, well done!

Do you have an ETA on the datetimepicker? :)

**Comment by alfonsobries** [comment]
Is in the plan but I been under a lot of work hope to have time for this next week but no promises

**Comment by DamianGlowala** [comment]
@alfonsobries Thank you for all the hard work on this library!

I'd like to follow up on the timepicker progress and kindly ask if we can expect a release anytime soon? If so, would you be able to provide any estimate on this?

**Comment by alfonsobries** [comment]
@DamianGlowala ill do my best to have it next week, already started
![image](https://user-images.githubusercontent.com/17262776/112414796-4dc52880-8ce8-11eb-9108-4410fab03659.png)

**Comment by alfonsobries** [comment]
good news @DamianGlowala @Reached I just released the time picker feature, just update to  `^2.2 ` and check the documentation https://www.vue-tailwind.com/docs/datepicker#timepicker

**Comment by Reached** [comment]
@alfonsobries well done!!
