### ISSUE TITLE
Classes aren't merged in markdown file with nuxt-content

### ISSUE THREAD

**Issue by ManUtopiK** [alfonsobries/vue-tailwind#142]
Thanks for your excellent components library!

Using with @nuxt/content plugin, vue-tailwind components in markdown files work great!
Exemple: `content/test.md`
```markdown
---
value: test
---
Some **markdown** here.

<t-input v-model="value"></t-input>

Markdown here again...
```
But now, if I add some classes on `t-input`, classes are not merged but override default classes.
```markdown
---
value: test
---
Some **markdown** here.

<t-input v-model="value" class="mt-2"></t-input>

Markdown here again...
```
Output: `<input data-v-f58a9f50="" type="text" class="mt-2">`

Is there a workaround to prevent this behavior?
I don't know if it's an issue from vue-tailwind or nuxt.
Should I submit this issue to @nuxt/content?

**Comment by alfonsobries** [comment]
@ManUtopiK no clue, the official docs use nuxt content and works fine, you can try to wrap the component on another component maybe?
