### ISSUE TITLE
Datepicker component not reading 'required' attribute

### ISSUE THREAD

**Issue by JosephELKHOURY** [alfonsobries/vue-tailwind#143]
Hello,

I'm using the Datepicker in my Laravel project and it's working great.
The only problem I'm facing is that even if I set the _required_ attribute to _true_, the form is ignoring the field.

Has anyone faced the same issue?

**Comment by alfonsobries** [comment]
Just fixed this issue, try to update to `2.1.2` 

Feel free to open the issue again if that doesnt work
