### ISSUE TITLE
Make Datepicker typeable

### ISSUE THREAD

**Issue by felixgoldstein** [alfonsobries/vue-tailwind#144]
Hi, 

great implementation of a datepicker.
I just was not able to find an option to allow the user type in dates manually. Is this somehow supported or planed to be implemented?

Thanks.

**Comment by alfonsobries** [comment]
@felixgoldstein since most of the time I can currently invest in this project is focused on the new vue3 version no plans to add to this version for now

Something I surely will consider for the new version of the package.
