### ISSUE TITLE
Datepicker defaulting to today (override)

### ISSUE THREAD

**Issue by Truemedia** [alfonsobries/vue-tailwind#145]
Hi,
I'm using the date picker to select historic data, so the dates for example might only occur in 2020 when the current year is 2021.

Using the built in props I can disable dates, navigation between months, and default to show the first month in the range fine.

My issue is when you click the datepicker a second time (maybe the user is revisiting the field) and it defaults to showing February 2021. This drops a user onto a broken view as they cannot select any dates on that month and takes a while to get back to the historic range.

Iv'e tried lots of ideas to no success and cannot find anything in the documentation to fix my edge case. Any ideas or is this potentially a problem that can be fixed with a new release if possible?

**Comment by alfonsobries** [comment]
Ok so I just found an issue, if I set the `initialDate` to a valid date in the range I want it works the first time, but if I remove the selected date and open the date picker again the date is today not the value on `initialDate`

its that the problem you are describing @Truemedia ?

**Comment by alfonsobries** [comment]
Update the library to `2.1.2` and use the `initialDate` prop to define the default active date, that should solve your problem.

if that doesnt work feel free to open this issue again

**Comment by Truemedia** [comment]
@alfonsobries Yes sorry for the late reply, yes that was my issue if I have any problems with the newer version I'll open another ticket thanks
