### ISSUE TITLE
TDialog as component does not return object with isOk: true when OK is pressed

### ISSUE THREAD

**Issue by esseremmerik** [alfonsobries/vue-tailwind#146]
Hi there,

Great work this toolset, saves a lot of time!

I believe there is an error with the current component usage of the TDialog. When used as a component, my response on the OK button is always isOK: false. When called programatically, there is no issue.
If you need more info, please let me know.

Peter

**Comment by esseremmerik** [comment]
I also see the "hideReason" set to "value" instead of "ok"/"cancel"

**Comment by alfonsobries** [comment]
@esseremmerik cannot see the issue are you adding the buttons manually or can I see a chunk of your code?

**Comment by alfonsobries** [comment]
Since no more info received ill close this ticket
