### ISSUE TITLE
[ Suggestion ] arrowWrapper / Arrow Slot on T-Rich Select

### ISSUE THREAD

**Issue by igerslike** [alfonsobries/vue-tailwind#148]
Would be perfect if we could costumize the t-rich-select arrow same way it does with the t-select to look like the native Tailwind Forms SVG dropdown arrow.

Sorry but i cannot push a PR as my TS skills are non-existent but looking forward to this! 

Keep up the great work.

**Comment by alfonsobries** [comment]
Sure @igerslike Im planning  to go over the open issues late today and I'll take care

**Comment by alfonsobries** [comment]
@igerslike now you can use the `arrow` slot if you update to `2.1.2`

**Comment by igerslike** [comment]
thanks a lot @alfonsobries ! <3
