### ISSUE TITLE
Dropdown Loading Issue

### ISSUE THREAD

**Issue by gego-soft** [alfonsobries/vue-tailwind#15]
I used Dropdown for menu, it works good. But it loads every time. See the video. 

https://drive.google.com/file/d/168lpNFNru5fdORWsddMugHDggEyvGSwE/view

Any fixes

Thanks in advance

**Comment by alfonsobries** [comment]
hi @gego-soft, currently im on vacations im back in a week, I will try to check the issue once I back

**Comment by alfonsobries** [comment]
@gego-soft you are adding the component inside a HTML template right? I mean is not a SPA or something? because you can use v-cloak attribute to load the component when its ready

v
https://vuejs.org/v2/api/#v-cloak

Not sure if that helps, let me know
