### ISSUE TITLE
Documentation site is broken

### ISSUE THREAD

**Issue by mmorainville** [alfonsobries/vue-tailwind#156]
Hi,

Great library! But the documentation site has 2 main issues on my side:
- If I click on a component, the URL changes but the page doesn't change, I have to either open the page in a new tab or manually refresh the page to see the content!
- The preview of the components is loading indefinitely. When checking the console, the following error appears:
`DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.`
It may be linked or not, but either way, it sadly does not make up for the best experience possible when discovering the lib.

**Comment by alfonsobries** [comment]
@mmorainville thanks for the report but cannot replicate it, did you notice the error on one specific page?

**Comment by mmorainville** [comment]
Hi @alfonsobries,

Well indeed I just checked right now and I can't reproduce neither of the two issues. And I reproduced several times and days in a row, in Chrome. Weird but cool! Closing this for now I guess!
