### ISSUE TITLE
Use it with nuxt js

### ISSUE THREAD

**Issue by allaghi** [alfonsobries/vue-tailwind#158]
Hi, 
Have a nice time,
I am wondering if I could use vue-taliwind with Nuxt js .

Thanks in advance.

**Comment by canthis** [comment]
@allaghi, of course You can!

1. Go to vue-tailwind's theme builder page and generate your theme - https://www.vue-tailwind.com/theme-builder
2. In your nuxt app `plugins` folder create file called `vue-tailwind.js` and put in it all the content provided by theme-builder from step 1
3. Add `vue-tailwind.js` plugin to your `nuxt.config.js` `plugins` array like that:
```
plugins: [
    '@/plugins/vue-tailwind',
],
``` 

Don't forget to install vue-tailwind package:
```
npm install --save vue-tailwind
// or 
yarn add vue-tailwind
```

**Comment by allaghi** [comment]
Thanks @canthis I will try it.

**Comment by alfonsobries** [comment]
As @canthis , closing this ticket for now

**Comment by luvejo** [comment]
Hi, @alfonsobries. What do you think about this StackOverflow [solution](https://stackoverflow.com/a/65781612)?

```js
import Vue from 'vue'
import { TDatepicker } from 'vue-tailwind/dist/components';
Vue.component('t-datepicker', TDatepicker)
```
