### ISSUE TITLE
valueAttribute and textAttribute for select not working but referenced in docs

### ISSUE THREAD

**Issue by mrdionjr** [alfonsobries/vue-tailwind#16]
I would like to set a custom value and text attribute for TSelect component but it is not working. Apparently theses props are not referenced in the component's props nor used in the template.

https://github.com/alfonsobries/vue-tailwind/blob/e8fd64328f068daa5222a2eba9ab25a192125114/src/elements/TSelect.vue#L33-L38

**Comment by alfonsobries** [comment]
These attributes are defined in this mixin https://github.com/alfonsobries/vue-tailwind/blob/master/src/mixins/hasMultioptions.js

Maybe if you share part of your code I can help?

**Comment by mrdionjr** [comment]
Closing this issue, since I was using an outdated version. Just updated to the latest version and it works now. Thanks
