### ISSUE TITLE
Multiple select css problem

### ISSUE THREAD

**Issue by nlv-edwinencomienda** [alfonsobries/vue-tailwind#161]
![image](https://user-images.githubusercontent.com/78135357/109597125-973faf00-7b52-11eb-9073-e169b51df408.png)

**Comment by alfonsobries** [comment]
Seems like some classes are missing for you select input, the multiple setting is new and it added a few classes keys:

Take a look at https://www.vue-tailwind.com/docs/rich-select#classes-and-variants-format

selectButtonTagWrapper | Div that wraps the tags on the multiselect
selectButtonTag | Multiselect option tag
selectButtonTagText | Multiselect option tag text
selectButtonTagDeleteButton | Multiselect option tag delete button
selectButtonTagDeleteButtonIcon | Multiselect option tag delete button icon

you may need to define those classes ^, you can use the default theme as starting point https://www.vue-tailwind.com/docs/rich-select#default-fixed-classes

**Comment by nlv-edwinencomienda** [comment]
thank you @alfonsobries  that's it  👏
