### ISSUE TITLE
[Question] Removal of wrapping div from TInputGroup body

### ISSUE THREAD

**Issue by DamianGlowala** [alfonsobries/vue-tailwind#162]
Would it be possible to remove the div wrapper for the TInputGroup content? I cannot apply border-red-(...) class for danger variant of the input inside TInputGroup tags, as instead of having it applied to the input element directly, it gets applied to the outer div...

Is there any reason for why the outer div is kept, or asking differently - how could I achieve applying this class using the VueTailwind config rather than repeating the class manually for every input?

**Comment by alfonsobries** [comment]
@DamianGlowala not sure if I get your question, maybe some example could help

You can use the `fixedClasses` setting to define a set of classes that are always applied or use the variants to only override one key of the template.

**Comment by DamianGlowala** [comment]
Basically the error variant of TInputGroup applies border-red-500 class to the div in which the body of TInputGroup is. It slightly defeats the purpose of having a variant with `body: "border-red-500"`. If I wanted to have such wrapper, I could create it myself and instead benefit of applying variant classes to the input by default.

![image](https://user-images.githubusercontent.com/48835293/109966934-19fe7080-7cf1-11eb-9164-d63c2f4bd359.png)
![image](https://user-images.githubusercontent.com/48835293/109967120-516d1d00-7cf1-11eb-8943-ebd84e3d34f0.png)
![image](https://user-images.githubusercontent.com/48835293/109967635-f38d0500-7cf1-11eb-9c30-65ea74c71d04.png)
