### ISSUE TITLE
Add support for lazy text inputs

### ISSUE THREAD

**Issue by Benjamin-Lee** [alfonsobries/vue-tailwind#164]
Right now, there's no way to prevent modeled variables from being changed immediately. Bootstrap-Vue solves this with a `lazy` prop, btw.

**Comment by alfonsobries** [comment]
definitely @Benjamin-Lee 

ill add this to my to-do list

**Comment by alfonsobries** [comment]
Ill add this on the vue3 version https://github.com/alfonsobries/vue-tailwind/issues/214

**Comment by tobiasdiez** [comment]
Instead of using a `lazy` prop as bootstrap-vue does, I would propose to support the `v-model.lazy` modifier https://vuejs.org/v2/guide/forms.html#lazy (if this is possible). In the past this was hard to implement, but maybe got easier with vue3? See https://github.com/vuejs/vue/issues/5743
