### ISSUE TITLE
export 'default' was not found in 'vue-tailwind'

### ISSUE THREAD

**Issue by wdiechmann** [alfonsobries/vue-tailwind#165]
I must be doing something wrong :( 

Plain out-of-the-box ~~everything~~ Vue works perfectly 🥳 

The minute I try to add ~~something~~Vue Tailwind (2.1.3) - I get this

```
hermes_1    | 
hermes_1    | ERROR in ./app/javascript/packs/hermes_vue.js 33:15-21
hermes_1    | "export 'TInput' was not found in 'vue-tailwind/dist/components/'
hermes_1    | 
hermes_1    | ERROR in ./app/javascript/packs/hermes_vue.js 39:8-19
hermes_1    | "export 'default' (imported as 'VueTailwind') was not found in 'vue-tailwind'
hermes_1    | 

```

My app.vue has one added element

```
<template>
  <div id="app">
    <t-input />
    <p>{{ message }}</p>
  </div>
</template>

```

and my javascript-pack mentions this

```

import Vue from 'vue'
import VueTailwind from 'vue-tailwind'
import App from '../components/app.vue'

import {
  TInput,
} from 'vue-tailwind/dist/components/'

const components = {
  't-input': {
    component: TInput,
    props: {
      classes: 'border-2 block w-full rounded text-gray-800'
    }
  }
}

Vue.use(VueTailwind, components)

document.addEventListener('DOMContentLoaded', () => {
  const app = new Vue({
    render: h => h(App)
  }).$mount()
  document.body.appendChild(app.$el)

  console.log(app)
})

```

**Comment by wdiechmann** [comment]
my devtools console tells me that

```
Uncaught TypeError: Cannot read property 'extend' of undefined
    at vue-tailwind.js:129
    at vue-tailwind.js:6
    at Module../node_modules/vue-tailwind/dist/vue-tailwind.js (vue-tailwind.js:7)
    at __webpack_require__ (bootstrap:19)
    at Module../app/javascript/packs/hermes_vue.js (hermes_vue.js:1)
```

**Comment by alfonsobries** [comment]
@wdiechmann 

If you need to import a single component the right way to do it is like explained here:

https://www.vue-tailwind.com/docs/installation#33-or-you-can-install-only-the-components-you-need

So your import is incorrect you should use `import TInput from 'vue-tailwind/dist/t-input'`

**Comment by wdiechmann** [comment]
Dear Alfonso

Please excuse my temper but -

This is exactly what I hate about this giant pile of s…. - one huge stack of dependencies one on top of the other amassing to a spaghetti of convoluted fog

import VueTailwind from 'vue-tailwind'
// import TInput from 'vue-tailwind/dist/t-input'

settings = {
}

Vue.use(VueTailwind, settings)


Even without importing any components - I get

hermes_1    | 
hermes_1    | ERROR in ./app/javascript/packs/hermes_vue.js 12:8-19
hermes_1    | "export 'default' (imported as 'VueTailwind') was not found in 'vue-tailwind'
hermes_1    | 


Uncaught TypeError: Cannot read property 'extend' of undefined
    at vue-tailwind.js:129
    at vue-tailwind.js:6
    at Module../node_modules/vue-tailwind/dist/vue-tailwind.js (vue-tailwind.js:7)
    at __webpack_require__ (bootstrap:19)
    at Module../app/javascript/packs/hermes_vue.js (hermes_vue.js:1)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83




Walther Højgaard Diechmann
Drosselvej 21
DK-8600  Silkeborg
tlf. +45 5365 2455
***@***.*** ***@***.***>

**Comment by alfonsobries** [comment]
@wdiechmann which version of Vue you are using?

**Comment by wdiechmann** [comment]
{
  "name": "hermes",
  "private": true,
  "dependencies": {
    ***@***.***/turbo-rails": "^7.0.0-beta.5",
    ***@***.***/actioncable": "^6.0.0",
    ***@***.***/actiontext": "^6.1.3",
    ***@***.***/activestorage": "^6.0.0",
    ***@***.***/ujs": "^6.0.0",
    ***@***.***/webpacker": "5.2.1",
    ***@***.***/aspect-ratio": "^0.2.0",
    ***@***.***/forms": "^0.2.1",
    ***@***.***/typography": "^0.4.0",
    "alpine-magic-helpers": "^1.0.0",
    "alpine-turbo-drive-adapter": "^1.0.1",
    "alpinejs": "^2.8.1",
    "apollo-boost": "^0.4.9",
    "autoprefixer": "^9",
    "coffee-loader": "0.9.0",
    "coffeescript": "1.12.7",
    "graphql": "^15.5.0",
    "postcss": "^7",
    "stimulus": "^2.0.0",
    "tailwindcss": ***@***.***/postcss7-compat",
    "trix": "^1.2.0",
    "vue": "^2.6.12",
    "vue-apollo": "^3.0.7",
    "vue-loader": "^15.9.6",
    "vue-tailwind": "^2.1.3",
    "vue-template-compiler": "^2.6.12"
  },
  "version": "0.1.0",
  "devDependencies": {
    "webpack-dev-server": "^3.11.2"
  }
}



Walther Højgaard Diechmann
Drosselvej 21
DK-8600  Silkeborg
tlf. +45 5365 2455
***@***.*** ***@***.***>

**Comment by wdiechmann** [comment]
It’s 3:30 in the morning - I have to go to bed :(

If I can offer any more information to help you help me understand what I am doing wrong - please do not hesitate to ask 


BR
Walther

**Comment by wdiechmann** [comment]
for what it's worth - I tried imitating your dependency graph with

```

const Component = Vue.extend({
  // ...
})

const HtmlInput = Component.extend({
  // ...
})

const TextInput = HtmlInput.extend({
  // ...
});


const TInput = TextInput.extend({
  // ...
});

```

and it compiles!

I get an "unknown custom element" but I guess that's just me being a total n00b around Vue 😢 

I've added Apollo (GraphQL client) and apart from a learning curve, I'm happy to report that 

```
import ApolloClient from 'apollo-boost'

```

works flawless

That, however, posits the question: Then, WTF, is going on?

**Comment by wdiechmann** [comment]
okay - now I followed https://medium.com/swlh/how-to-integrate-vue-js-with-rails-6-5bd4c6263b18 to the letter and verified that Vue does it's magic and says Hello 😄 

then I followed the https://www.vue-tailwind.com/docs/installation item 1,2 and 3 - and then I get:

```
Version: webpack 4.46.0
Time: 86ms
Built at: 10.03.2021 16.28.41
                                     Asset       Size       Chunks                         Chunk Names
    js/application-5fa1f55cbfe14af14893.js    5.7 MiB  application  [immutable]            application
js/application-5fa1f55cbfe14af14893.js.map   6.08 MiB  application  [dev]                  application
      js/hello_vue-1bdd7a61a4d67107a0ae.js   1.13 MiB    hello_vue  [emitted] [immutable]  hello_vue
  js/hello_vue-1bdd7a61a4d67107a0ae.js.map   1.33 MiB    hello_vue  [emitted] [dev]        hello_vue
                             manifest.json  689 bytes               [emitted]              

ERROR in ./app/javascript/packs/hello_vue.js 54:8-19
"export 'default' (imported as 'VueTailwind') was not found in 'vue-tailwind'
    at HarmonyImportSpecifierDependency._getErrors (/Users/walther/src/templates/vue-template/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (/Users/walther/src/templates/vue-template/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/walther/src/templates/vue-template/node_modules/webpack/lib/Compilation.js:1463:22)
    at /Users/walther/src/templates/vue-template/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/walther/src/templates/vue-template/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/walther/src/templates/vue-template/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/Users/walther/src/templates/vue-template/node_modules/webpack/lib/Compilation.js:1253:28)
    at /Users/walther/src/templates/vue-template/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/Users/walther/src/templates/vue-template/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/Users/walther/src/templates/vue-template/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:56:22)
    at /Users/walther/src/templates/vue-template/node_modules/webpack/lib/Compilation.js:1185:12
    at /Users/walther/src/templates/vue-template/node_modules/webpack/lib/Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
ℹ ｢wdm｣: Failed to compile.

```

I have assembled what I like to think of as the important parts here:
https://gist.github.com/wdiechmann/c179eb88bb4c769b89719215bcda2cd1

**Comment by robtesch** [comment]
For what it's worth, I'm having the exact same issue. I've even tried to "v1 syntax" approach and I'm just getting:

`export 'VueTailwind' (imported as 'VueTailwind') was not found in 'vue-tailwind' (module has no exports)`

**Comment by robtesch** [comment]
@wdiechmann did you ever find a resolution to this issue?

**Comment by wdiechmann** [comment]
@robtesch nah - @alfonsobries gave me directions (that I was not able to follow) so ...

But our current package.json looks like

```
    "dependencies": {
        "@hotwired/turbo-rails": "^7.0.0-beta.5",
        "@johmun/vue-tags-input": "^2.1.0",
        "@rails/actioncable": "^6.0.0",
        "@rails/actiontext": "^6.1.3",
        "@rails/activestorage": "^6.0.0",
        "@rails/ujs": "^6.0.0",
        "@rails/webpacker": "5.2.1",
        "@tailwindcss/aspect-ratio": "^0.2.0",
        "@tailwindcss/forms": "^0.2.1",
        "@tailwindcss/typography": "^0.4.0",
        "alpine-magic-helpers": "^1.0.0",
        "alpine-turbo-drive-adapter": "^1.0.1",
        "alpinejs": "^2.8.1",
        "apollo-boost": "^0.4.9",
        "autoprefixer": "^9",
        "coffee-loader": "0.9.0",
        "coffeescript": "1.12.7",
        "dayjs": "^1.10.4",
        "dayjs-dynamic-locale": "^0.0.7",
        "graphql": "^15.5.0",
        "luxon": "^1.26.0",
        "postcss": "^7",
        "stimulus": "^2.0.0",
        "tailwindcss": "npm:@tailwindcss/postcss7-compat",
        "trix": "^1.2.0",
        "vue": "^2.6.12",
        "vue-advanced-search": "^0.1.43",
        "vue-apollo": "^3.0.7",
        "vue-datetime": "^1.0.0-beta.14",
        "vue-loader": "^15.9.6",
        "vue-tailwind": "^2.2.1",
        "vue-tailwind-datetime-picker": "^1.1.1",
        "vue-tailwind-picker": "^2.0.0",
        "vue-template-compiler": "^2.6.12",
        "vue2-datepicker": "^3.9.0",
        "weekstart": "^1.1.0"
    },
```
and (one of) my "packs" - appointment.js looks like this

```
import Vue from 'vue'
import Datepicker from '../components/datepicker.vue'
import Autocomplete from '../components/autocomplete.vue'

```

so I guess we went with the "railsy" way of doing stuff - using Stimulus - which I am saddened by because I really like the Alpine thinking but hey, you know, when things don't move you gotta make decisions right? 😃

**Comment by robtesch** [comment]
Thanks for the input. I've managed to get things moving myself just now by changing my webpack config so that it doesn't use babel-loader anymore. I have no idea what I'm doing when it comes to webpack so I just tried stuff until suddenly things worked.

**Comment by wdiechmann** [comment]
@robtesch and that is boiled to the bone exactly my sentiment with regards to webpacker (and friends)

there is simply too many moving cogs and pins in that stack!

TailwindCSS is perfect - the JIT though already is forcing me to cargo-cult with 27 deps and another 17 devdeps

AlpineJS is fine too - but even that has 16 devdeps and my guess is that by June 16th it will have another 5-10 deps and this all leads straight to DLL-hell (like why I switched to mac in 2006 when I was on 8 daily reboot's due to dll's colliding on M$ windozes 😉
