### ISSUE TITLE
Rich select visual bug when multiple selected

### ISSUE THREAD

**Issue by Mlekar** [alfonsobries/vue-tailwind#168]
There's a visual bug / issue with the rich select component in multi select mode. When you search for an option (via the search box) and already have some options selected, if you select a new one the existing option tags will disappear from the select input (while staying selected, visible in the dropdown).

You can replicate this on the docs page, if you search for ''Option A'' in the example and select it, option B and option C will disappear from the input.

**Comment by alfonsobries** [comment]
@Mlekar should be fixed on v 2.1.4
