### ISSUE TITLE
Use portal for rich select

### ISSUE THREAD

**Issue by jaulz** [alfonsobries/vue-tailwind#173]
I noticed that rich select components do not work well in containers that have hidden overflows. Is there any plan to use a portal for the rich select?

**Comment by alfonsobries** [comment]
@jaulz not for this version of the package but is something I'll try to implement in the v3 if I found a way to keep it simple

**Comment by jaulz** [comment]
@alfonsobries exciting 😊  will v3 be for Vue 3 or also for Vue 2?

**Comment by alfonsobries** [comment]
@jaulz vue 3

**Comment by razbakov** [comment]
Experiencing the same problem. I am trying to make a horizontally scrollable list of filters like on Airbnb
