### ISSUE TITLE
Date picker placeholder not working

### ISSUE THREAD

**Issue by edwinencomienda** [alfonsobries/vue-tailwind#179]
Placeholder date picker not working and showing only not required

![image](https://user-images.githubusercontent.com/26597108/113463327-c26e3480-9457-11eb-9ed0-58d54858c4aa.png)

**Comment by alfonsobries** [comment]
@edwinencomienda just upgrade the package to the Latest version that was a typo I introduced by mistake on 2.1.2 but was fixed in the next releases

**Comment by edwinencomienda** [comment]
yeah fixed when upgrading thanks @alfonsobries
