### ISSUE TITLE
Multiple radio groups on the same page have duplicate ids

### ISSUE THREAD

**Issue by atymic** [alfonsobries/vue-tailwind#18]
When you have multiple options groups on the same page, they end up with duplicate ids. This means clicking the first item on the last group on the page with focus your cursor/select the first item of the first group on the page.

I'll PR a fix when I have time.

**Comment by alfonsobries** [comment]
Thanks I also take a look later today

**Comment by atymic** [comment]
I've managed to solve the issue for the time being by setting the `name` prop, which becomes part of the `id` attribute. 

Maybe automatically generating a random name when one isn't provided?
