### ISSUE TITLE
Upgrade to postcss 8

### ISSUE THREAD

**Issue by tobiasdiez** [alfonsobries/vue-tailwind#180]
Currently, vue-tailwind declares the dependencies
```
postcss "^7"
tailwindcss "npm:@tailwindcss/postcss7-compat"
```
It would be nice if you could upgrade this to postcss 8 and remove the tailwind compatibility tag.

**Comment by 19peaches** [comment]
Yeah this is an interesting package, way too much config really, but not using all the current requirements of Tailwind is a dealbreaker.

**Comment by alfonsobries** [comment]
@tobiasdiez tailwindcss/postcss is now a dev dependency so you can use whatever you like 

It should have been like that from the beginning. I don't know how they got as dependencies.

**Comment by alfonsobries** [comment]
Closing this but feel free to open if you have something more to add
