### ISSUE TITLE
Documentation: Dont mention to install Tailwind Dependency

### ISSUE THREAD

**Issue by JoshDev1205** [alfonsobries/vue-tailwind#20]
Good Morning

I saw in the Docs that you dont mention to install Talwindcss like project dependency.

![image](https://user-images.githubusercontent.com/20880980/65338867-b631c780-db90-11e9-9d0e-f86726545dbc.png)

I think its important to mention it because someone can assume that the package have tailwindcss inside.

Good Job :+1:

**Comment by alfonsobries** [comment]
Thanks for noticing, ill update the docs

**Comment by alfonsobries** [comment]
Fixed, thanks
