### ISSUE TITLE
Component Request: Tabs

### ISSUE THREAD

**Issue by timothymarois** [alfonsobries/vue-tailwind#202]
Hello, I noticed there weren't any tab components, you have tables, modals, dropdowns which are advanced from standard HTML wrappers like most of the other utility-based components you have. I think another great essential component should have `<t-tabs>`, just wanted to see what your thoughts are here and if there are any plans to add this. Thanks. Nice work on everything else so far!

**Comment by timothymarois** [comment]
Looks like this library is dead. Will no longer be using it since the support isn't there. I know how hard it is to keep an open-source package going, it's unfortunate cause this was a really nice and simple library. Looks like the author has moved on.

**Comment by alfonsobries** [comment]
@timothymarois not dead but most of my energy is on the new version so if you need a faster support probably using another alternative is the best option 

Pd There are many ways you can support the project that help me to increase the time i spent on it 😉
