### ISSUE TITLE
Using with Nuxt & vue Composition API

### ISSUE THREAD

**Issue by andyjamesn** [alfonsobries/vue-tailwind#205]
Hi, I am aware this will not work with Vue 3 but I am using Nuxt with the composition API which works.. sort of..

I can for example trigger a dialog using a click event in the <template>

```
<button
    @click="
      $dialog
        .confirm(
          'Reset all?',
          'This action cannot be undone.',
          'warning'
        )
        .then((result) => {
          if (result.isOk) reset();
        })
    "
  >
```

Obviously this is not ideal. Do you have any idea how I could access $dialog from inside the setup() method as this.$dialog is not available. But since it works in the template as shown above I can't help but think there must be a way.

**Comment by alfonsobries** [comment]
cannot say if it's possible so help you with that will require to dig into the code, mount a nuxt app etc, nothing I can do right now, so closing for now
