### ISSUE TITLE
[BUG] Needs to be updated to Vue 2.6.14

### ISSUE THREAD

**Issue by 19peaches** [alfonsobries/vue-tailwind#206]
Alphonso,

Version 2.3.0 and below will no longer install for the current version of Nuxt (2.15.7) as it requires Vue assets 2.6.14

```
vue
vue-template-compiler
```

I think that's all but there could be more.

**Comment by Mlekar** [comment]
Also just getting errors when trying to build assets, since there's a version mismatch for the Vue and Vue-template-compiler libs if you update them (since this package still depends on the older versions)

**Comment by elliotsoomro** [comment]
Can confirm this. Can't run npm run dev since it produces Nuxt Fatal Error, Vue packages version mismatch
- vue@2.6.13
- vue-server-renderer@2.6.14

**Comment by 6XGate** [comment]
This does beg the question; why the peer dependency is so strict and not using `^`?

**Comment by alfonsobries** [comment]
Thanks for the report I'll fix this tonight

**Comment by alfonsobries** [comment]
@19peaches @6XGate @Mlekar @elliotsoomro 

Just updated the library to use a flexible version of vue, upgrade the lib and `^2.4.0` let me know if that fixes your problem

**Comment by Mlekar** [comment]
You still have Vue 2.6.13 listed as a peerDependency in your package.json, which causes errors / warnings when updating via NPM

**Comment by alfonsobries** [comment]
@Mlekar right updated only dev dependencies 😅, should be fixed on `^2.4.1`

**Comment by 6XGate** [comment]
Just recently tried the latest release against 2.6.14 myself with no issues
