### ISSUE TITLE
Treeshaking

### ISSUE THREAD

**Issue by ais-one** [alfonsobries/vue-tailwind#21]
Hi, are we able to pick and choose the components to use? Reduce bundle size?

**Comment by alfonsobries** [comment]
Probably it is but need to make a quick test to be sure, Ill make the test tonight and if not possible adjust the repository to do that, and of course the docs, definitely an important feature.

**Comment by ais-one** [comment]
great thanks... it will drive adoption, great work!

**Comment by alfonsobries** [comment]
@ais-one Just updated the ccomponents to be self installable in #22 

Also updated the docs with further explanation https://github.com/alfonsobries/vue-tailwind#install-only-the-components-you-need
