### ISSUE TITLE
'white-space-no' instead of 'white-space-normal' in rich select component

### ISSUE THREAD

**Issue by onmax** [alfonsobries/vue-tailwind#229]
In the [TRichSelect config file](https://github.com/alfonsobries/vue-tailwind/blob/21f6d5f97fa167948422c5b0ef8ffa8252b7c756/src/components/TRichSelect.ts#L105), the classname `white-space-no` is being used. But, the real class name in Tailwind is `white-space-normal`. See [official documentation](https://tailwindcss.com/docs/whitespace#normal)

**Comment by alfonsobries** [comment]
@onmax thanks fixed on `2.5.0` with the `whitespace-nowrap ` class
