### ISSUE TITLE
IE11 Bug - duplicate property definitions 

### ISSUE THREAD

**Issue by atymic** [alfonsobries/vue-tailwind#24]
This causes my app to break on IE11. I managed to trace it back to the checkbox element, where it defines `v-model` and `value`, which breaks ie completely :(

https://forum.vuejs.org/t/ie-issue-propertie-not-allowed-in-strict-mode-and-blank-page-result/21443

I'll see if I can figure out a fix.

**Comment by alfonsobries** [comment]
Ok thanks, I do my best to fix this today, I been speciallly busy these days, also stilll have pending the other bug you send me.

Thanks!

**Comment by atymic** [comment]
No worries, thanks for the update :)
