### ISSUE TITLE
Pagination in Rich Select

### ISSUE THREAD

**Issue by eguidotti** [alfonsobries/vue-tailwind#248]
Hi there, and thanks for this great framework!

I'm trying to implement a rich select that pulls the data from an API and displays the results in a dropdown menu. The results can be many and they should be paginated, e.g., with a load-more button or infinite-scroll in the dropdown.

I followed your example [here](https://www.vue-tailwind.com/docs/rich-select) and it works great, but I can't find any example on pagination. From the [docs](https://www.vue-tailwind.com/docs/rich-select#props), I read that `fetchOptions` is a:

> Method for fetching the options, receives the `query` as string and the `nextPage` if apply

My callback for `fetchOptions` receives the query but not the `nextPage`. How should I do to enable pagination (`nextPage`) in the rich-select? Many thanks!

**Comment by eguidotti** [comment]
Any hint so far? :(

**Comment by dasturchiuz** [comment]
```
 returened_data.hasMorePages = {
                    nextPage: data.current_page + 1
                };
```

**Comment by eguidotti** [comment]
Thanks! It seems that the value of `nextPage` is irrelevant. To turn pagination on, I just set `hasMorePages` to `true`

```js
return {results: options, hasMorePages: options.length > 0 ? true : false}
```

Cheers
