### ISSUE TITLE
Checkbox not working, value never changes

### ISSUE THREAD

**Issue by msslgomez** [alfonsobries/vue-tailwind#257]
How am I supposed to use the checkbox correctly, it doesn't work how I would expect. When I click on the checkbox the field `form.remember` never changes even as the checkbox is being checked and unchecked.

```
<template>
    <t-checkbox wrapped :model="form.remember">Remember me</t-checkbox>
</template>

<script>
export default {
    data() {
        return {
            form: this.$inertia.form({
                email: '',
                password: '',
                remember: false
            })
        }
    },
}
```

**Comment by alfonsobries** [comment]
> How am I supposed to use the checkbox correctly, it doesn't work how I would expect. When I click on the checkbox the field `form.remember` never changes even as the checkbox is being checked and unchecked.
> 
> 
> 
> ```
> 
> <template>
> 
>     <t-checkbox wrapped :model="form.remember">Remember me</t-checkbox>
> 
> </template>
> 
> 
> 
> <script>
> 
> export default {
> 
>     data() {
> 
>         return {
> 
>             form: this.$inertia.form({
> 
>                 email: '',
> 
>                 password: '',
> 
>                 remember: false
> 
>             })
> 
>         }
> 
>     },
> 
> }
> 
> ```

You can create your own library

**Comment by msslgomez** [comment]
🙃 I like this library. Thanks I guess.
