### ISSUE TITLE
Usage in Laravel throws Module not found: Can't resolve 'vue-tailwind'

### ISSUE THREAD

**Issue by obsessen** [alfonsobries/vue-tailwind#26]
Hello, I'm trying to use your package in a Laravel application, but when I try to build the javascript it throws: `Module not found: Error: Can't resolve 'vue-tailwind'`

If I change the import from:
`import VueTailwind from 'vue-tailwind`
to:
`import VueTailwind from 'vue-tailwind`
it starts working.

**Comment by alfonsobries** [comment]
Yeah already defected that error temporally please use the version 0.3 I let you know once the patch is ready

**Comment by alfonsobries** [comment]
@obsessen fixed please upgrade the package to latest version `0.4.1`

**Comment by obsessen** [comment]
@alfonsobries it works, thank you!
