### ISSUE TITLE
How i can add selected attribute to t-select component?

### ISSUE THREAD

**Issue by gnujach** [alfonsobries/vue-tailwind#30]
Hi, someone can help me, i need add _selected_ attribute to <t-select> but i know not, this is my code:
Thanks advance!!
`<t-select
              id="genero"
              v-model="genero"
              name="genero"
              :options="[
                    { key: 'H', description: 'Hombre' },
                    { key: 'M', description: 'Mujer' },
                ]"
              value-attribute="key"
              text-attribute="description"
              base-class="block appearance-none w-full border-2 border-blue-300 pr-8 rounded-lg leading-tight bg-blue-100"
              required
            />`
I try with this code without success:
`  :options="[
                    { key: 'H', description: 'Hombre', **selected: true** },
                    { key: 'M', description: 'Mujer' },
                ]"`

**Comment by maverick504** [comment]
Hi!

You should set the desired value to be selected in the attribute you are using for `v-model`, that in your case is `genero`.

So in your data method, you should have:

```
  data: function () {
    return {
      form: new Form({
        ...
        genero: 'M',
        ...
      })
    }
  }
```

You can also use the `mounted` method to set the selected value if you are fetching data from de DB.

**Comment by alfonsobries** [comment]
Yeah as @maverick504 mention just use the `v-model` or `:value`

```
<t-select
:value="'M'"
// rest of the attribs
/>
```

```
<t-select
v-model="genero'"
// rest of the attribs
/>

// genero = 'M'
```

**Comment by gnujach** [comment]
Thank very  much, this works for me.
