### ISSUE TITLE
Not working after 0.4.2

### ISSUE THREAD

**Issue by adamwhitlock1** [alfonsobries/vue-tailwind#37]
The package.json appears to be using an entry point of:

`"main": "./dist/vue-tailwind.common.js",`

That file seems to not be getting built when v0.4.4 is being installed. It works if I install 0.4.2 though.

**Comment by francoisauclair911** [comment]
Same

**Comment by alfonsobries** [comment]
Make a mistake when publishing is fixed now in `0.4.5`
