### ISSUE TITLE
Should have support for percentage

### ISSUE THREAD

**Issue by figurluk** [alfonsobries/vue-tailwind#39]
https://github.com/alfonsobries/vue-tailwind/blob/be8816c715b8272b0e323294df58e90ff3bbec8f/src/components/TModal.vue#L190

**Comment by alfonsobries** [comment]
agree will work in that ASAP

**Comment by runyasak** [comment]
I have submitted PR #46 to resolve this issue, please review on my code. 😁

**Comment by alfonsobries** [comment]
Already fixed in v0 and v1 thanks!
