### ISSUE TITLE
Thoughts on integrating with `vue-formulate`

### ISSUE THREAD

**Issue by hacknug** [alfonsobries/vue-tailwind#50]
I've been looking into simplifying all of my Vue+forms mess by using `vue-formulate` to handle everything from data-binding to validation. The only issue I have with the library is that building custom controls from scratch every time make me feel like I'm wasting my life.

Have you considered turning your components in a UI-only version of them that integrates with the mentioned package or something similar? You'd save some time writing most of that logic and I think everything would be easier to extend/compose.

**Comment by alfonsobries** [comment]
@hacknug I don't want to make this library more big/complex and stick with the idea of have customizable components with fewer dependencies as possible, take care of the validation or integrate with another library means adding dependencies and not all users need validation, just as an example I personally not a big fan of the client-side validations I prefer to validate the forms in the backend.

However, the idea of adding standalone and optional "plugins" like one to integrate validation seems like a good idea but currently, my priorities include vue3 support and a few more missing common components like the date picker or the dialog, once I finish with that is for sure something I can considerate
