### ISSUE TITLE
Cannot find module '@/types/CssClass'

### ISSUE THREAD

**Issue by moodyVlad** [alfonsobries/vue-tailwind#74]
ERROR in D:/Code/Exenzo/jobboost.io-app/node_modules/vue-tailwind/dist/components/TDatepicker.d.ts(1,43)
Cannot find module '@/utils/dates'
ERROR in D:/Code/Exenzo/jobboost.io-app/node_modules/vue-tailwind/dist/components/TPagination.d.ts(2,22):
Cannot find module '@/types/CssClass'.

And many others, it seems that the internal aliases are not working.

**Comment by alfonsobries** [comment]
thanks for the report ill take a look later today

**Comment by alfonsobries** [comment]
just one question @moodyVlad this happens to you after you install the library I suppose?

**Comment by moodyVlad** [comment]
Hey, had version 0.45. After installing 1.2.6 this happens. Maybe some conflict eith my tsconfig?

**Comment by alfonsobries** [comment]
@moodyVlad Are you installing the component directly, can you share with me your settings?

**Comment by moodyVlad** [comment]
Just ran npm i --save vue-tailwind@^1.2.6.

**Comment by alfonsobries** [comment]
@moodyVlad Sorry maybe I wasnt clear I mean how you're importing/configuring the library or the component, consider that the version `1.x` and the version  `0.x` are completely different so the syntax for importing and configure it are different

**Comment by moodyVlad** [comment]
in my main.ts

import VueTailwind from "vue-tailwind";

Vue.use(VueTailwind, {});

**Comment by alfonsobries** [comment]
Ok I was unable to replicate the problem but I think the next release should solve the problem

Can I ask you for a favor? 

Install the version in this PR: https://github.com/alfonsobries/vue-tailwind/pull/75

Just run 

` npm i --save vue-tailwind@next`

And let my know if solve your issue

**Comment by moodyVlad** [comment]
Worked

**Comment by alfonsobries** [comment]
@moodyVlad Ok just tagged this patch, I recommend you to update to the stable version instead of `@next` that includes this patch to avoid issues in the future

the version is `1.2.7`
