### ISSUE TITLE
DatePicker does not overflow div

### ISSUE THREAD

**Issue by Benjamest** [alfonsobries/vue-tailwind#76]
Hello,

I've attached an image - I thought it would be easier than try to explain as a newbie! It seems like the datepicker does not overflow outside of a typically styled div: https://imgur.com/a/zB3IHKg

**Comment by damian-bal** [comment]
You could probably fix it by changing z-index of main calendar element.

**Comment by alfonsobries** [comment]
@Benjamest according to the screenshot the problem should be in the card not in the date picker, try adding `overflow-visible` class to the card.

**Comment by alfonsobries** [comment]
I will close this issue since no new comments added
