### ISSUE TITLE
Modal not scrolling

### ISSUE THREAD

**Issue by esezen** [alfonsobries/vue-tailwind#77]
I have a modal with this configuration. 
```
  TModal: {
    fixedClasses: {
      overlay:
        'z-40 overflow-auto left-0 top-0 bottom-0 right-0 w-full h-full fixed bg-opacity-50 flex',
      wrapper: 'z-50 relative mx-auto my-auto max-w-lg lg:max-w-6xl',
      modal: 'bg-white shadow overflow-hidden relative',
      body: 'p-4',
      header: 'p-4  text-sm font-semibold uppercase text-gray-700',
      footer: 'p-4 text-sm font-semibold uppercase text-gray-700 flex justify-center',
      close: 'absolute right-0 top-0 m-3 text-gray-700 hover:text-gray-600',
      closeIcon: 'h-5 w-5 fill-current',
    },
    classes: {
      overlay: 'bg-black ',
      wrapper: '',
      modal: '',
      body: 'p-4',
      header: 'text-gray-700 border-b',
      footer: 'border-t ',
      close: 'text-gray-700 hover:text-gray-600',
      closeIcon: '',
    },
    variants: {
      danger: {
        overlay: 'bg-red-500',
        header: 'border-red-100 text-red-700 border-b',
        footer: 'border-red-100 bg-red-100 border-t  ',
        close: 'text-red-700 hover:text-red-600',
      },
      clean: {
        modal: 'rounded shadow-lg',
        footer: 'bg-gray-100 ',
        body: 'p-4 text-sm text-gray-700',
        close:
          'bg-blue-100 p-1 flex items-center justify-center leading-normal rounded-full text-blue-80 hover:bg-blue-200',
      },
    },

```

When the modal pops up, it is scrollable on desktop or in the chrome emulator. However, the modal is not scrollable on an actual mobile phone. The page is shorter than the mobile phone screen but the modal gets longer than that. I checked the body that and the overflow-hidden gets added to there. So it is not like the body is preventing the modal from scrolling. I also tried adding overflow-y-scroll to different parts but no luck.

Thanks in advance.

**Comment by alfonsobries** [comment]
@esezen I test your exact same settings in a fresh page, create a long modal, and cannot replicate the problem it may be related to where the modal is added, like let say a div with an overflow or weird stuff like that, is hard to know,

If you can give a link to test the modal or some way to replicate the issue I may be able to help

**Comment by esezen** [comment]
Thanks for the quick reply and for your attention. Can I send you a message on twitter with the link? It is a semi-private app in development.

**Comment by alfonsobries** [comment]
@esezen Fixed the error in this PR https://github.com/alfonsobries/vue-tailwind/pull/78

Just update the library to the v1.x and ensure to add `scrolling-touch` class to the "fixedClasses.overlay" of your template

thanks for the report
