### ISSUE TITLE
There are some mistyped words in documentation

### ISSUE THREAD

**Issue by faizalami** [alfonsobries/vue-tailwind#79]
Hello, i found some mistyped words and some examples that might be wrong in the documentation.

First I found some mistyped words in [card documentation](https://www.vue-tailwind.com/docs/card), I think this is because you are copy and paste from modal documentation :laughing:, so the word 'modal' in there should be 'card'.

Then I also found a strange example in [using modal global methods documentation](https://www.vue-tailwind.com/docs/modal#3-using-the-name-of-the-modal-with-the-built-in-global-methods), I feel there are some mistakes there, and also there is one missing closing bracket.

I suggest you to re-check the documentation, may be there are some other mistakes in there.

**Comment by alfonsobries** [comment]
hey @faizalami thanks for the advice I will fix those and take a second look to the docs
