### ISSUE TITLE
Settings not working with storybook

### ISSUE THREAD

**Issue by dsfx3d** [alfonsobries/vue-tailwind#83]
I'm working with a design system and writing a components library which is running on storybook.

I've installed the plugin like this,

```javascript
import Vue from 'vue'
import VueTailwind from 'vue-tailwind'

import { settings } from './settings'

Vue.use(VueTailwind, settings)
```

When I run the app on the development server, the components get styled as expected.
But when I use those components inside a story, the styles I've configured in _settings.js_ are missing.

I checked the browser's dev tools and found that none of the configured classes gets assigned to the HTML elements.
Although, it works fine if I explicitly assign those classes in the story.

for eg.
I have a _.button_ class for the `TButton` component. I've added it to the _fixedClasses_ of the `TButton` component in _settings.js_.

The class gets assigned to the component if I serve the project on the development server but is missing if I use the same component in a story.

It only works If I pass in the _.button_ class explicitly in the story's _args_.

This is what my story looks like:

```javascript
import { TButton } from 'vue-tailwind'

export default {
  title: 'Example/Button',
  component: TButton,
  argTypes: {
    variant: {
      control: { type: 'select', options: ['', 'primary'] }
    },
    onClick: { action: 'click' }
  }
}

const Template = (_args, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: { TButton },
  template: `
    <t-button @click="onClick" v-bind="$props">
      Button
    </t-button>`
})

export const Default = Template.bind({})
Default.args = {
  class: 'button'
}

export const Primary = Template.bind({})
Primary.args = {
  variant: 'primary'
}
```

Settings for TButton:

```javascript
export const TButton = {
  fixedClasses: 'button',
  variants: {
    primary: 'is-primary'
  }
}
```

It works in the `Default` story because I'm explicitly passing the _button_ class but not in the `Primary` story.

although it doesn't make sense but I even tried extending the component like this,

```javascript
<template>
  <t-button v-bind="$props" v-on="$listeners">
    <slot />
  </t-button>
</template>

<script>
import { TButton } from 'vue-tailwind'

export default {
  name: 'AppButton',
  components: { TButton },
  extends: TButton
}
</script>
```
It still doesn't work

**Comment by alfonsobries** [comment]
I have no experience with storybook (I have plans to use for the next version of the docs), anyway, you can install the plugin normally? with the `Vue.use(` syntax?

Ask because it's possible to install a single component but you should use the same syntax you use to install the library since the installation process is when the props are overridden, to do that you need to import the component like this: `vue-tailwind/dist/components/`

example `import ComponentName from 'vue-tailwind/dist/components/ComponentName.umd.js'`

```
import TButton from 'vue-tailwind/dist/components/TButton.umd.js'

Vue.use(TButton, {
   fixedClasses: 'button',
  variants: {
    primary: 'is-primary'
  }
})
```

Notice that this is not in the docs, the main reason is that I am not happy with the approach I followed and is something I want to change in the next version of the package that very likely will accept a syntax like the one you are using.

Let me know if that syntax helps you, I am very interested in making this library works with storybook

**Comment by dsfx3d** [comment]
@alfonsobries the plugin works fine, it was a mistake on my end.
Instead of using the globally registered component in the story, I was importing the component and then using it.

The story should look like this if someone else faces this issue in future:

```javascript
export default {
  title: 'Example/Button',
  component: TButton,
  argTypes: {
    variant: {
      control: { type: 'select', options: ['', 'primary'] }
    },
    onClick: { action: 'click' }
  }
}

const Template = (_args, { argTypes }) => ({
  props: Object.keys(argTypes),
  // The component is already globally registered and configured,
  // do not register the component locally
  // components: { TButton },
  template: `
    <t-button @click="onClick" v-bind="$props">
      Button
    </t-button>`
})

export const Primary = Template.bind({})
Primary.args = {
  variant: 'primary'
}
```
