### ISSUE TITLE
How to merge multiple variants?

### ISSUE THREAD

**Issue by Lacroute** [alfonsobries/vue-tailwind#84]
Hi,

Hi have button with variants: `primary` and `secondary`. I also have a variant `disabled` with deals with opacity. I want to have a `primary disabled` button, but according to the doc, only one variant at a time can affect my button.

It can also happen if I have some variants for size like `small`, `medium`, `big`, so question is how to have a `small primary` variant?

How to deal with that?

thanks

**Comment by alfonsobries** [comment]
There is no way to merge them as you probably thinking, you need to create more variants like `smallPrimary`, `mediumSecondary`, etc, the version 0 of this library used to have that feature but after used it a lot I noticed that this make the library less flexible so also no plans to add that feature.

For the disabled inputs you have 3 options:
- If you are using tailwind as your CSS library you can enable the `:disabled` pseudo variant 
(https://tailwindcss.com/docs/pseudo-class-variants#disabled) < that's the best option  and then add classes like `disabled:opacity-50`
- If you are using your own CSS library you can create a class like that one ^ 
- The last option is to create another variant like `disabledPrimary` but of course, means complexity.

**Comment by Lacroute** [comment]
I'll go with the disabled variant for this case.
Just to be sure to understand, there is no way to use the responsive variants from tailwind inside vue-tailwind?
