### ISSUE TITLE
Use after helper to configure variants

### ISSUE THREAD

**Issue by Lacroute** [alfonsobries/vue-tailwind#86]
Hi,

I think taking advantage of [after/before](qr5zxs7xas3hluw9kjxx78cng46rqxnj) helpers could be a good idea instead of hard coding variants like here > https://github.com/alfonsobries/vue-tailwind/blob/4c335b09235b6a197a9a562d62c073342fedaec8/tailwind.config.js#L7

**Comment by alfonsobries** [comment]
@Lacroute the tailwind.config.js file inside the library is just for developing purpose (to manual test the library while I work in it) it shouldn't be used directly since is different for every one.
