### ISSUE TITLE
vuejs v3 support

### ISSUE THREAD

**Issue by dcyou** [alfonsobries/vue-tailwind#88]
Hi, 
Vue3 plan to be support?

thanks

**Comment by dcyou** [comment]
found https://www.vue-tailwind.com/docs/upcoming-changes but any more precise information

**Comment by alfonsobries** [comment]
hey @dcyou yes is part of the plan but I don't have a specific date I expect to release it in about 3 months

**Comment by dcyou** [comment]
thanks ;)

**Comment by aislanmaia** [comment]
Excited about Vue 3 support!!
How can we help to speed up ?
