### ISSUE TITLE
Using custom setter for computed properties fires an extra trigger

### ISSUE THREAD

**Issue by Lacroute** [alfonsobries/vue-tailwind#89]
Hi,

I'm binding a `v-model` to my `vuex` store using v-model and custom getter and setter. I noticed that if I use a custom setter with a t-element it fires two times. First when there is an update, then after the update.

reproduction link (without vuex)> https://codesandbox.io/s/sleepy-ritchie-r59ej?file=/src/CustomComputed.vue

There is no consequences with my data, but I want to avoid useless updates because it creates unwanted API calls.

**Comment by alfonsobries** [comment]
@Lacroute I see, yeah that its a problem I'll take a look next week
