### ISSUE TITLE
this looks great but...

### ISSUE THREAD

**Issue by vesper8** [alfonsobries/vue-tailwind#9]
what the Tailwind community badly needs is someone to fork https://github.com/bootstrap-vue/bootstrap-vue and make it all work with Tailwind instead of Bootstrap!!

Maybe that someone could be you.. Since you've already begun ;-)

**Comment by alfonsobries** [comment]
Yeah that's an option but I personally prefer to have more control over the components, I use it myself in my projects, also is a personal challenge an exercise, so I will leave the current path as is it for now
