### ISSUE TITLE
Table data cannot be loaded asynchronously

### ISSUE THREAD

**Issue by emertechie** [alfonsobries/vue-tailwind#90]
Pretty much as title says. If `t-table` is bound to a `tableData` array, and that array is populated after the initial rendering of the table, no rows are rendered.

**Comment by alfonsobries** [comment]
Its possible to have a reproduction link or a chunk of your code cannot replicate any error

**Comment by alfonsobries** [comment]
I'll close this issue for now since cannot reproduce the problem, if you have more info feel free to open the issue again @emertechie
