### ISSUE TITLE
t-radio-group type validation error 

### ISSUE THREAD

**Issue by Lacroute** [alfonsobries/vue-tailwind#91]
Hi,

Not a big deal but I got this warning during the use of `t-radio-group`. I didn't check on other components.

`Invalid prop: type check failed for prop "value". Expected String, Number, got Boolean with value false.`

reproduction link > [https://codesandbox.io/s/epic-currying-yhjxk?file=/src/App.vue](https://codesandbox.io/s/epic-currying-yhjxk?file=/src/App.vue)

**Comment by alfonsobries** [comment]
@Lacroute fixed in the v1.3.x
