### ISSUE TITLE
Dialog missing styles

### ISSUE THREAD

**Issue by Sch-Tomi** [alfonsobries/vue-tailwind#95]
Hi!

First of all thanks for this plugin, it's such a pleasure to use.

I think I just find some bug, with the [programmatically way](https://www.vue-tailwind.com/docs/dialog#open-the-dialog-programmatically) of open the dialog.

First of all, I pasted the default classes from the theme builder. So I have a danger variant.
When I create a dialog as a [component](https://www.vue-tailwind.com/docs/dialog#as-vue-componen), everything work as expected, red button, red background. 

But when I use the programmatically call, its break. The dialog hasn't got any styles. 
I only used the examples found in the docs.

Did I missed something, or is it a bug?

**Comment by Sch-Tomi** [comment]
Oh and its only break when I use the `variant: "danger"` prop. If I didn't use the `variant` prop its work fine with the default styles

**Comment by alfonsobries** [comment]
Ok thanks for the report I’ll take a look once I’m in my computer

**Comment by alfonsobries** [comment]
@Sch-Tomi problem solved please update to the latest version of the package `^1.3.1`

**Comment by Sch-Tomi** [comment]
Thanks I'll check it
