### ISSUE TITLE
Incorrect date display with the parameter weekStart = 1

### ISSUE THREAD

**Issue by gerasimovs** [alfonsobries/vue-tailwind#96]
When the "weekStart" parameter is set to 1 in November 2020, the calendar is displayed incorrectly. It is stated that November 1 is Monday. All other months are working correctly:

```
TDatepicker: {
    weekStart: 1,
    dateFormat: 'Y-m-d',
    userFormat: 'd.m.Y',
},
```
![DatePicker](https://user-images.githubusercontent.com/20923969/98547237-72d17580-22ca-11eb-83f5-d9a9ae23661b.png)

**Comment by alfonsobries** [comment]
Hey just to ley you know that I already saw your issue, was especially busy the last week but ill take care of this tomorrow

**Comment by alfonsobries** [comment]
@gerasimovs problem solved please update to the latest version of the package `^1.3.1`
